# Generated by Django 5.1.4 on 2025-03-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderdetail_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderdetail",
            options={"verbose_name": "订单详情", "verbose_name_plural": "订单详情"},
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "未支付"),
                    ("PAID", "已支付"),
                    ("REFUNDED", "已退款"),
                ],
                default="UNPAID",
                max_length=10,
                verbose_name="支付状态",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
        ),
        migrations.AddField(
            model_name="order",
            name="trade_no",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="支付宝交易号"
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="orders.order",
                verbose_name="所属订单",
            ),
        ),
    ]
