"""
Django settings for bar_order_system project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j+uoplb__^_2k#wnl6^o_ci=!h^#qh=$bywn3#^x_vxb^!7kfa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'apps.products',
    'apps.orders',
    'apps.frontend',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bar_order_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bar_order_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bar_order_system',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'autocommit': True,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 用于生产环境收集静态文件

# 额外的静态文件目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# 允许的请求方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

# SWAGGER_SETTINGS
SWAGGER_SETTINGS = {
    'DEFAULT_INFO': None,
    'SECURITY_DEFINITIONS': None,
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
}

# 确保这些配置存在且正确
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]

CORS_ORIGIN_ALLOW_ALL = True  # 开发环境可以设置为 True

# 添加此配置
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]

# JWT配置
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# 支付宝网关地址
gateway = 'https://openapi-sandbox.dl.alipaydev.com/gateway.do'
# 支付宝APPID
APPID = '9021000140629275'
# 应用私钥，注意私钥内容需完整准确，且格式正确
private_key = 'MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCPM1JTsXJyJtj2AhyMj0/ZjRVotI025ECaoPFWHTKqMgSHMmJ/L5Dl7qVszmL1Lx/jxqrdl/toF497vWz/bY41ehDCtBknOSxqCHBrYc6WtjgFG/ByK9MPXTqN6f/8zfCB2YnJojfytj3nWC6Ac/nLNq3AeYMIwFgVxMtvtv2M/SZCvmcZmEGLB6S2VuofrH9HRVEpjW80tiX0wCCUshS0uzIc3P4CrGdA1+c2aTiSh6wbsVcSc8pEUS/HDr7AdYQAWY2nxOJKDcefVpTzSEfJCWyG+ZJ94MCH8TNez5oLKSOJVpAL4EWi8c4Z78QqXUdCGclq4hKnFpntEUygYtwZAgMBAAECggEAIxFNWuN8hEnRHcV8mktKIZt0H7T/U+7nhzZcg1sZGiavhzAmgMD0OeqMJi4Qe7xzkcMH+sYKMf57C7FirNZ2WdAvpI6YDkvo/XpdlV5ZSf0LkOy7oCntQLjy6uff4VfJSvMr0+3ex5grZqjoklpUVJhqSlU3aoA30fTkYNIuG0VQ4b2GWYEZBdcf6lAQRJf4deEnwGLMGVg5q79+ns/A152QiZwd6UN/0Kf4IIdne+lZuE9b4VFwhK0Jc6gFzm7g/QCzxLKMM4I7Hm1f2R5RFzL42hQCEwxqF6CZF7JfINzlSv29800O0YKdUuOCjFCsF0rMCzpHlni5+A2tKCXnEQKBgQDRLL2TLlvnE67X2Eqszr93qcRPX0eRndtHVq0qjCc4SV4COw/uu0D/dUVvx/V6s0JYDrK6wb0N8aeF6Y8ojd5q6uxRT+ur3Txj0pWzkp/3aJvlxi8U2h1d61k+lT4kl1ECi1b9kVexPJuUmVrc8YAyFydnCO/v2jSqLvLDysuo5QKBgQCvQcRGm3DjWBB3N/sRGuEtW6npYFEOONmDdQNe9ISMxPiYvfrxXVBd82vqgtRHIHMpb0jHyY37qb9Gen97zqEf4XqO/uJGQ39f/jGyzuzWNuwEp5s5n4Mt+ORRnk0gehzYDKQTyz8G64GM815oOMvZVeexEbjsD1iS+WpUvZ13JQKBgQC2CSOqFKwyOzTr7vV90idaskl/ccHM/f245bupzXLMTz0a39+LuTZlmt8k2nXNpHdWPuRYFwa6PdW2en31oxEvJucmFFFarhxCGx/guPexzj3uBz0t/muUMp7mEeeU3ILJng3EelpAiigzeApVQW55KSFHT8XPjKxMdrMapT/76QKBgGcp/ZHaml8ZTcf/6gitm/OJS8GW8t++Uzvwu2U/5m6+2999paRC27YSPmozTSX5UhEH8v24BZ4o0/F21mhYv7v2jKB0JVpbDTXCehrZd8y5U8GBr/wBi8SaCDyLRLdjams7NbJ5J8a5Bu+jquUK2eQ7j0FKP2Klvev2acMsQu8JAoGAAQnG8DxHFkYBBcjHsGH+c6ELOLG+x94bTdROMpmScaH8xemJbPTJzwJNE8t4fu5QxSIYvRTxKK7U3Ko1TX2pKRp/rvQxitGVMVUFBuSNXqPFUXqa4NV61Km33jTUlUIzrZeBQv/+6aMSbKWJtCA2um6+CGDi4tlckUNTZjxlQyQ='
# 支付宝公钥
public_key = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmp8aPBurMjEvgiLOrU60cIwXNjfeKNVySXXT8fBHfWLg+yBFktinT9jE13gyZK9kgvjO7G9LwNtL1vOTeg7E7JnGbvulMU7LeGJPUSWl/KOXuQcQYX8nsbdpC8e9Ki77+ifFCJLrRLiwydJCbqQOvhm6sGesqLFNZCxwx0KdZW2i05Mdy2pLZD0+bkQSQH2MCt3bNemXXZjKLwZbqy5/cHzSzVzuzNV24rGc/1v9yqYauxq1eeY3G2K90Hk6IdnQLCQkN4tvP/3iJZxdGeSfxtqYWN/8Ue8hlHI8/7YFWcgnfUuVnXEwCoV849DEzkN7mfCxuypXn/DqQvS5PMPudwIDAQAB'