# Generated by Django 4.2 on 2025-01-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('category', models.CharField(choices=[('BAIJIU', '白酒'), ('RED_WINE', '红酒'), ('BEER', '啤酒'), ('FOREIGN', '洋酒')], max_length=20, verbose_name='类别')),
                ('alcohol_content', models.FloatField(verbose_name='酒精度')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('temperature_requirement', models.CharField(choices=[('COLD', '冷饮'), ('HOT', '热饮'), ('BOTH', '冷热皆可')], max_length=10, verbose_name='温度要求')),
                ('description', models.TextField(verbose_name='描述')),
            ],
            options={
                'verbose_name': '酒品',
                'verbose_name_plural': '酒品',
            },
        ),
    ]
