# Generated by Django 5.1.4 on 2025-02-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "商品", "verbose_name_plural": "商品"},
        ),
        migrations.AlterField(
            model_name="product",
            name="alcohol_content",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="酒精度"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="product",
            name="temperature_requirement",
            field=models.CharField(
                choices=[("COLD", "冷饮"), ("HOT", "热饮"), ("BOTH", "冷热皆可")],
                default="COLD",
                max_length=10,
                verbose_name="温度要求",
            ),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
