# Generated by Django 5.1.4 on 2025-02-05 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_alter_product_options_alter_product_alcohol_content_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="products/%Y/%m",
                validators=[
                    django.core.validators.FileExtensionValidator(["jpg", "png"])
                ],
                verbose_name="商品图片",
            ),
        ),
    ]
